### ISSUE TITLE
online dating 👎👎👎👎👎👎👎👎👎👎👎👎👎👎👎

### ISSUE THREAD

**Issue by reddogsliketofart** [AfaGaming/TinDog#1]
online dating is being promoted towards young generations. take this down now!!!!!!!!!!!!!!!!!! 😡😡😡😡😡😡😡😡😡

**Comment by AfaGaming** [comment]
Thanks for bringing this to my attention. However, this is a **DOG** dating site not humans. This is an absolutely useless use of the issues tab.

**Comment by AfaGaming** [comment]
Post locked.
